parameters:
- name: 'environment'
  type: string

jobs:
- job: Pulumi
  steps:
  - task: Bash@3
    name: npmInstall
    displayName: NPM Install
    inputs:
        targetType: 'inline'
        script: npm i

  - task: Bash@3
    name: pulumiLogin
    displayName: Pulumi Login
    inputs:
        targetType: 'inline'
        script: pulumi login
    env:
      PULUMI_ACCESS_TOKEN: $(PULUMI_ACCESS_TOKEN)

  - task: Bash@3
    name: pulumiStackSelect
    displayName: Pulumi Stack Select
    inputs:
        targetType: 'inline'
        script: pulumi stack select ${{ parameters.environment }} -c --non-interactive

  - task: Bash@3
    name: pulumiUp
    displayName: Pulumi Up
    inputs:
        targetType: 'inline'
        script: pulumi up -y
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      ENVIRONMENT: ${{ parameters.environment }}
