# Trigger on any push to main
trigger:
  - master

pr: none

pool:
  vmImage: ubuntu-20.04

variables:
- group: "Deploy"

stages:
  - stage: Deploy_Dev
    displayName: Deploy Infrastructure
    jobs:
      - template: deploy_template.yaml
        parameters:
          environment: 'dev'

  - stage: Deploy_Qa
    displayName: Deploy QA Infrastructure
    jobs:
      - template: deploy_template.yaml
        parameters:
          environment: 'qa'
